import React from "react";
import HTwo from "../../components/UI/Legal/HTwo";
import HThree from "../../components/UI/Legal/HThree";
import Section from "../../components/UI/Legal/Section";
import P from "../../components/UI/Legal/P";

const Privacy = () => {
  return (
    <div className="py-8 px-16 mx-auto">
      <h1 className="font-bold text-4xl text-center mb-4">PRIVACY POLICY</h1>
      <p>Last updated: 08/02/2022</p>
      <Section>
        <HTwo>
          1. <span className="underline">Introduction</span>
        </HTwo>
        <P>
          Welcome to <span className="font-bold">todidit.com</span>.
        </P>
        <P>
          todidit.com (<span className="font-bold">“us”, “we”, or “our”</span>)
          operates http://www.todidit.com and toDidit mobile
          application (hereinafter referred to as{" "}
          <span className="font-bold"> “Service”</span>).
        </P>
        <P>
          Our Privacy Policy governs your visit to http://www.todidit.com and
          toDidit mobile application, and explains how we collect, safeguard and
          disclose information that results from your use of our Service.{" "}
        </P>
        <P>
          We use your data to provide and improve Service. By using Service, you
          agree to the collection and use of information in accordance with this
          policy. Unless otherwise defined in this Privacy Policy, the terms
          used in this Privacy Policy have the same meanings as in our Terms and
          Conditions.
        </P>
        <P>
          Our Terms and Conditions (<span className="font-bold">“Terms”</span>)
          govern all use of our Service and together with the Privacy Policy
          constitutes your agreement with us (
          <span className="font-bold">“agreement”</span>).
        </P>
      </Section>
      <Section>
        <HTwo>
          2. <span className="underline">Definitions</span>
        </HTwo>
        <P>
          <span className="font-bold">SERVICE</span> means
          the http://www.todidit.com website and toDidit mobile
          application operated by todidit.com.
        </P>
        <P>
          <span className="font-bold">PERSONAL DATA</span> means data about a
          living individual who can be identified from those data (or from those
          and other information either in our possession or likely to come into
          our possession).
        </P>
        <P>
          <span className="font-bold">USAGE DATA</span> is data collected
          automatically either generated by the use of Service or from Service
          infrastructure itself (for example, the duration of a page visit).{" "}
        </P>
        <P>
          <span className="font-bold">COOKIES</span>are small files stored on
          your device (computer or mobile device).
        </P>
        <P>
          <span className="font-bold">DATA CONTROLLER </span>means a natural or
          legal person who (either alone or jointly or in common with other
          persons) determines the purposes for which and the manner in which any
          personal data are, or are to be, processed. For the purpose of this
          Privacy Policy, we are a Data Controller of your data.
        </P>
        <P>
          <span className="font-bold">
            DATA PROCESSORS (OR SERVICE PROVIDERS) 
          </span>
          means any natural or legal person who processes the data on behalf of
          the Data Controller. We may use the services of various Service
          Providers in order to process your data more effectively.
        </P>
        <P>
          <span className="font-bold">DATA SUBJECT </span>is any living
          individual who is the subject of Personal Data.
        </P>
        <P>
          <span className="font-bold">THE USER</span> is the individual using
          our Service. The User corresponds to the Data Subject, who is the
          subject of Personal Data.
        </P>
      </Section>
      <Section>
        <HTwo>
          3. <span className="underline">Information Collection and Use</span>
        </HTwo>
        <P>
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </P>
      </Section>
      <Section>
        <HTwo>
          4. <span className="underline">Types of Data Collected</span>
        </HTwo>
        <HThree>Personal Data</HThree>
        <P>
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you (<span className="font-bold">“Personal Data”</span>).
          Personally identifiable information may include, but is not limited
          to:
        </P>
        <ol className="pl-20 flex flex-col gap-4 list-decimal">
          <li>Email address</li>
          <li>Cookies and Usage Data</li>
        </ol>
        <P>
          We may use your Personal Data to contact you with newsletters,
          marketing or promotional materials and other information that may be
          of interest to you. You may opt out of receiving any, or all, of these
          communications from us by following the unsubscribe link or by
          emailing at support@todidit.com.
        </P>
        <HThree>Usage Data</HThree>
        <P>
          We may also collect information that your browser sends whenever you
          visit our Service or when you access Service by or through a mobile
          device (<span className="font-bold">“Usage Data”</span>).
        </P>
        <P>
          This Usage Data may include information such as your computer's
          Internet Protocol address (e.g. IP address), browser type, browser
          version, the pages of our Service that you visit, the time and date of
          your visit, the time spent on those pages, unique device identifiers
          and other diagnostic data.
        </P>
        <P>
          When you access Service with a mobile device, this Usage Data may
          include information such as the type of mobile device you use, your
          mobile device unique ID, the IP address of your mobile device, your
          mobile operating system, the type of mobile Internet browser you use,
          unique device identifiers and other diagnostic data.
        </P>
        <HThree>Tracking Cookies Data</HThree>
        <P>
          We use cookies and similar tracking technologies to track the activity
          on our Service and we hold certain information.
        </P>
        <P>
          Cookies are files with a small amount of data which may include an
          anonymous unique identifier. Cookies are sent to your browser from a
          website and stored on your device. Other tracking technologies are
          also used such as beacons, tags and scripts to collect and track
          information and to improve and analyze our Service.
        </P>
        <P>
          You can instruct your browser to refuse all cookies or to indicate
          when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of our Service.
        </P>
        <P>Examples of Cookies we use:</P>
        <ol className="pl-20 flex flex-col gap-4 list-decimal">
          <li>
            <span className="font-bold"> Session Cookies: </span>We use Session
            Cookies to operate our Service.
          </li>
          <li>
            <span className="font-bold"> Preference Cookies:</span> We use
            Preference Cookies to remember your preferences and various
            settings.
          </li>
          <li>
            <span className="font-bold"> Security Cookies:</span> We use
            Security Cookies for security purposes.
          </li>
          <li>
            <span className="font-bold"> Advertising Cookies:</span> Advertising
            Cookies are used to serve you with advertisements that may be
            relevant to you and your interests.
          </li>
        </ol>
      </Section>
      <Section>
        <HTwo>
          5. <span className="underline">Use of Data</span>
        </HTwo>
        <P>todidit.com uses the collected data for various purposes:</P>
        <ol className="pl-20 flex flex-col gap-4 list-decimal">
          <li>to provide and maintain our Service;</li>
          <li>to notify you about changes to our Service; </li>
          <li>
            to allow you to participate in interactive features of our Service
            when you choose to do so;{" "}
          </li>
          <li>to provide customer support; </li>
          <li>
            to gather analysis or valuable information so that we can improve
            our Service;{" "}
          </li>
          <li>to monitor the usage of our Service;</li>
          <li>to detect, prevent and address technical issues;</li>
          <li>to fulfill any other purpose for which you provide it;</li>
          <li>
            to carry out our obligations and enforce our rights arising from any
            contracts entered into between you and us, including for billing and
            collection;
          </li>
          <li>
            to provide you with notices about your account and/or subscription,
            including expiration and renewal notices, email-instructions, etc.;
          </li>
          <li>
            to provide you with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless you have opted not to receive such information;
          </li>
          <li>
            in any other way we may describe when you provide the information;
          </li>
          <li>for any other purpose with your consent. </li>
        </ol>
      </Section>
      <Section>
        <HTwo>
          6. <span className="underline">Retention of Data</span>
        </HTwo>
        <P>
          We will retain your Personal Data only for as long as is necessary for
          the purposes set out in this Privacy Policy. We will retain and use
          your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to
          comply with applicable laws), resolve disputes, and enforce our legal
          agreements and policies.
        </P>
        <P>
          We will also retain Usage Data for internal analysis purposes. Usage
          Data is generally retained for a shorter period, except when this data
          is used to strengthen the security or to improve the functionality of
          our Service, or we are legally obligated to retain this data for
          longer time periods.
        </P>
      </Section>
      <Section>
        <HTwo>
          7. <span className="underline">Transfer of Data</span>
        </HTwo>
        <P>
          Your information, including Personal Data, may be transferred to – and
          maintained on – computers located outside of your state, province,
          country or other governmental jurisdiction where the data protection
          laws may differ from those of your jurisdiction.
        </P>
        <P>
          If you are located outside United States and choose to provide
          information to us, please note that we transfer the data, including
          Personal Data, to United States and process it there.
        </P>
        <P>
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </P>
        <P>
          todidit.com will take all the steps reasonably necessary to ensure
          that your data is treated securely and in accordance with this Privacy
          Policy and no transfer of your Personal Data will take place to an
          organisation or a country unless there are adequate controls in place
          including the security of your data and other personal information.
        </P>
      </Section>
      <Section>
        <HTwo>
          8. <span className="underline">Disclosure of Data</span>
        </HTwo>
        <P>
          We may disclose personal information that we collect, or you provide:
        </P>

        <ol className="pl-20 flex flex-col gap-4 list-decimal">
          <li>
            <span className="font-bold">Disclosure for Law Enforcement.</span>
            <p>
              Under certain circumstances, we may be required to disclose your
              Personal Data if required to do so by law or in response to valid
              requests by public authorities.
            </p>
          </li>
          <li>
            <span className="font-bold">Business Transaction.</span>
            <p>
              If we or our subsidiaries are involved in a merger, acquisition or
              asset sale, your Personal Data may be transferred.
            </p>
          </li>
          <li>
            <span className="font-bold">
              Other cases. We may disclose your information also:
            </span>
            <ol className="list-disc pl-6">
              <li>to our subsidiaries and affiliates;</li>
              <li>
                to contractors, service providers, and other third parties we
                use to support our business;
              </li>
              <li>with your consent in any other cases;</li>
              <li>
                if we believe disclosure is necessary or appropriate to protect
                the rights, property, or safety of the Company, our customers,
                or others.
              </li>
            </ol>
          </li>
        </ol>
      </Section>
      <Section>
        <HTwo>
          9. <span className="underline">Security of Data</span>
        </HTwo>
        <P>
          The security of your data is important to us but remember that no
          method of transmission over the Internet or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
        </P>
      </Section>
      <Section>
        <HTwo>
          10.{" "}
          <span className="underline">
            Your Data Protection Rights Under General Data Protection Regulation
            (GDPR)
          </span>
        </HTwo>
        <P>
          If you are a resident of the European Union (EU) and European Economic
          Area (EEA), you have certain data protection rights, covered by GDPR.
          – See more at{" "}
          <a
            target="_blank"
            className="link text-blue-600 hover:text-blue-800 visited:text-purple-600"
            href="https://eur-lex.europa.eu/eli/reg/2016/679/oj"
          >
            {" "}
            https://eur-lex.europa.eu/eli/reg/2016/679/oj
          </a>{" "}
        </P>
        <P>
          We aim to take reasonable steps to allow you to correct, amend,
          delete, or limit the use of your Personal Data.
        </P>
        <P>
          If you wish to be informed what Personal Data we hold about you and if
          you want it to be removed from our systems, please email us at
          support@todidit.com.{" "}
        </P>
        <P>
          In certain circumstances, you have the following data protection
          rights:
        </P>
        <ol className="pl-20 flex flex-col gap-4 list-decimal">
          <li>
            the right to access, update or to delete the information we have on
            you;
          </li>
          <li>
            the right of rectification. You have the right to have your
            information rectified if that information is inaccurate or
            incomplete;
          </li>
          <li>
            the right to object. You have the right to object to our processing
            of your Personal Data;
          </li>
          <li>
            the right of restriction. You have the right to request that we
            restrict the processing of your personal information;
          </li>
          <li>
            the right to data portability. You have the right to be provided
            with a copy of your Personal Data in a structured, machine-readable
            and commonly used format;
          </li>
          <li>
            the right to withdraw consent. You also have the right to withdraw
            your consent at any time where we rely on your consent to process
            your personal information;
          </li>
        </ol>
        <P>
          Please note that we may ask you to verify your identity before
          responding to such requests. Please note, we may not able to provide
          Service without some necessary data.
        </P>
        <P>
          You have the right to complain to a Data Protection Authority about
          our collection and use of your Personal Data. For more information,
          please contact your local data protection authority in the European
          Economic Area (EEA).
        </P>
      </Section>
      <Section>
        <HTwo>
          11.{" "}
          <span className="underline">
            Your Data Protection Rights under the California Privacy Protection
            Act (CalOPPA)
          </span>
        </HTwo>
        <P>
          CalOPPA is the first state law in the nation to require commercial
          websites and online services to post a privacy policy. The law’s reach
          stretches well beyond California to require a person or company in the
          United States (and conceivable the world) that operates websites
          collecting personally identifiable information from California
          consumers to post a conspicuous privacy policy on its website stating
          exactly the information being collected and those individuals with
          whom it is being shared, and to comply with this policy. – See more
          at:{" "}
          <a
            target="_blank"
            className="link text-blue-600 hover:text-blue-800 visited:text-purple-600"
            href="https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/"
          >
            https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/
          </a>{" "}
        </P>
        <P>According to CalOPPA we agree to the following:</P>
        <ol className="pl-20 flex flex-col gap-4 list-decimal">
          <li>users can visit our site anonymously;</li>
          <li>
            our Privacy Policy link includes the word “Privacy”, and can easily
            be found on the page specified above on the home page of our
            website;
          </li>
          <li>
            users will be notified of any privacy policy changes on our Privacy
            Policy Page;
          </li>
          <li>
            users are able to change their personal information by emailing us
            at support@todidit.com.{" "}
          </li>
        </ol>
        <P>Our Policy on “Do Not Track” Signals:</P>
        <P>
          We honor Do Not Track signals and do not track, plant cookies, or use
          advertising when a Do Not Track browser mechanism is in place. Do Not
          Track is a preference you can set in your web browser to inform
          websites that you do not want to be tracked.{" "}
        </P>
        <P>
          You can enable or disable Do Not Track by visiting the Preferences or
          Settings page of your web browser.
        </P>
      </Section>
      <Section>
        <HTwo>
          12. <span className="underline">Service Providers</span>
        </HTwo>
        <P>
          We may employ third party companies and individuals to facilitate our
          Service (<span className="font-bold">“Service Providers”</span>),
          provide Service on our behalf, perform Service-related services or
          assist us in analysing how our Service is used.
        </P>
        <P>
          These third parties have access to your Personal Data only to perform
          these tasks on our behalf and are obligated not to disclose or use it
          for any other purpose.
        </P>
      </Section>
      <Section>
        <HTwo>
          13. <span className="underline">Analytics</span>
        </HTwo>
        <P>
          We may use third-party Service Providers to monitor and analyze the
          use of our Service.
        </P>
        <HThree>Google Analytics</HThree>
        <P>
          Google Analytics is a web analytics service offered by Google that
          tracks and reports website traffic. Google uses the data collected to
          track and monitor the use of our Service. This data is shared with
          other Google services. Google may use the collected data to
          contextualise and personalise the ads of its own advertising network.
        </P>
        <P>
          For more information on the privacy practices of Google, please visit
          the Google Privacy Terms web page:
          <a
            target="_blank"
            className="link text-blue-600 hover:text-blue-800 visited:text-purple-600"
            href="https://policies.google.com/privacy?hl=en"
          >
            {" "}
            https://policies.google.com/privacy?hl=en
          </a>
        </P>
        <P>
          We also encourage you to review the Google's policy for safeguarding
          your data:{" "}
          <a
            target="_blank"
            className="link text-blue-600 hover:text-blue-800 visited:text-purple-600"
            href="https://support.google.com/analytics/answer/6004245"
          >
            https://support.google.com/analytics/answer/6004245.
          </a>
        </P>
        <HThree>Piwik / Matomo</HThree>
        <P>
          Piwik or Matomo is a web analytics service. You can visit their
          Privacy Policy page here:{" "}
          <a
            target="_blank"
            className="link text-blue-600 hover:text-blue-800 visited:text-purple-600"
            href="https://matomo.org/privacy-policy"
          >
            https://matomo.org/privacy-policy
          </a>
        </P>
        <HThree>Clicky</HThree>
        <P>
          Clicky is a web analytics service. Read the Privacy Policy for Clicky
          here:
          <a
            target="_blank"
            className="link text-blue-600 hover:text-blue-800 visited:text-purple-600"
            href=" https://clicky.com/terms"
          >
             https://clicky.com/terms
          </a>
        </P>
        <HThree>Cloudflare analytics</HThree>
        <P>
          Cloudflare analytics is a web analytics service operated by Cloudflare
          Inc. Read the Privacy Policy here:
          <a
            target="_blank"
            className="link text-blue-600 hover:text-blue-800 visited:text-purple-600"
            href="https://www.cloudflare.com/privacypolicy/"
          >
            {" "}
            https://www.cloudflare.com/privacypolicy/
          </a>
        </P>
        <HThree>Mixpanel</HThree>
        <P>Mixpanel is provided by Mixpanel Inc.</P>
        <P>
          You can prevent Mixpanel from using your information for analytics
          purposes by opting-out. To opt-out of Mixpanel service, please visit
          this page:
          <a
            target="_blank"
            className="link text-blue-600 hover:text-blue-800 visited:text-purple-600"
            href="https://mixpanel.com/optout/"
          >
            {" "}
            https://mixpanel.com/optout/
          </a>
        </P>
        <P>
          For more information on what type of information Mixpanel collects,
          please visit the Terms of Use page of Mixpanel:
          <a
            target="_blank"
            className="link text-blue-600 hover:text-blue-800 visited:text-purple-600"
            href="https://mixpanel.com/terms/"
          >
            {" "}
            https://mixpanel.com/terms/
          </a>
        </P>
      </Section>
      <Section>
        <HTwo>
          14. <span className="underline">CI/CD Tools</span>
        </HTwo>
        <P>
          We may use third-party Service Providers to automate the development
          process of our Service.{" "}
        </P>
        <HThree>GitHub</HThree>
        <P>GitHub is provided by GitHub, Inc.</P>
        <P>
          GitHub is a development platform to host and review code, manage
          projects, and build software.
        </P>
        <P>
          For more information on what data GitHub collects for what purpose and
          how the protection of the data is ensured, please visit GitHub Privacy
          Policy page:
          <a
            target="_blank"
            className="link text-blue-600 hover:text-blue-800 visited:text-purple-600"
            href="https://help.github.com/en/articles/github-privacy-statement"
          >
            {" "}
            https://help.github.com/en/articles/github-privacy-statement
          </a>
          .
        </P>
        <HThree>GitLab CI/CD</HThree>
        <P>GitLab CI/CD is provided by GitLab, Inc.</P>
        <P>
          GitLab CI (Continuous Integration) service is a part of GitLab that
          build and test the software whenever developer pushes code to
          application.{" "}
        </P>
        <P>
          GitLab CD (Continuous Deployment) is a software service that places
          the changes of every code in the production which results in every day
          deployment of production.{" "}
        </P>
        <P>
          For more information on what data GitLab CI/CD collects for what
          purpose and how the protection of the data is ensured, please visit
          GitLab CI/CD Privacy Policy page:
          <a
            target="_blank"
            className="link text-blue-600 hover:text-blue-800 visited:text-purple-600"
            href="https://about.gitlab.com/privacy/"
          >
            {" "}
            https://about.gitlab.com/privacy/
          </a>
          .
        </P>
        <HThree>CircleCI</HThree>
        <P>CircleCI is provided by Circle Internet Services, Inc.</P>
        <P>
          CircleCI is Continuous Integration, a development practice which is
          being used by software teams allowing them to build, test and deploy
          applications easier and quicker on multiple platforms.{" "}
        </P>
        <P>
          For more information on what data Circle CI collects for what purpose
          and how the protection of the data is ensured, please visit Circle CI
          Privacy Policy page:
          <a
            target="_blank"
            className="link text-blue-600 hover:text-blue-800 visited:text-purple-600"
            href="https://circleci.com/privacy/"
          >
            {" "}
            https://circleci.com/privacy/
          </a>
          .{" "}
        </P>
      </Section>
      <Section>
        <HTwo>
          15. <span className="underline">Links to Other Sites</span>
        </HTwo>
        <P>
          Our Service may contain links to other sites that are not operated by
          us. If you click a third party link, you will be directed to that
          third party's site. We strongly advise you to review the Privacy
          Policy of every site you visit.
        </P>
        <P>
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </P>
      </Section>
      <Section>
        <HTwo>
          16. <span className="underline">Children's Privacy</span>
        </HTwo>
        <P>
          Our Services are not intended for use by children under the age of 18
          (<span className="font-bold">“Child”</span> or{" "}
          <span className="font-bold">“Children”</span>).{" "}
        </P>
        <P>
          We do not knowingly collect personally identifiable information from
          Children under 18. If you become aware that a Child has provided us
          with Personal Data, please contact us. If we become aware that we have
          collected Personal Data from Children without verification of parental
          consent, we take steps to remove that information from our servers.
        </P>
      </Section>
      <Section>
        <HTwo>
          17. <span className="underline">Changes to this Privacy Policy</span>
        </HTwo>
        <P>
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page.
        </P>
        <P>
          We will let you know via email and/or a prominent notice on our
          Service, prior to the change becoming effective and update “effective
          date” at the top of this Privacy Policy.
        </P>
        <P>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </P>
      </Section>
      <Section>
        <HTwo>
          18. <span className="underline">Contact Us</span>
        </HTwo>
        <P>
          If you have any questions about this Privacy Policy, please contact
          us:
        </P>
        <P>By email: support@todidit.com.</P>
      </Section>
    </div>
  );
};

export default Privacy;
